project_name: "X3D"
exp_name: 'X3D'
use_wandb: False
wandb_entity: 

# dataset
train_root: '/home/aiot/Rity/split_data/data/train_data' # Update the path to match your local setup
test_root: '/home/aiot/Rity/split_data/data/test_data'
clip_length: 16
data_size: [112, 112] # H, W
num_workers: 8
batch_size: 16

# model setting
num_classes: 4
model_size: 'm'
torch_pretrained: True

seed: 42

max_epochs: 100
warmup_batchs: 10
wdecay: 0.0001
momentum: 0.9
# learning rate schedule setting
lr_schedule:
    name: 'cosine_decay' # ['linear', 'step', 'cosine'] + '_decay or '_increase
    min_value: 0.000000000025
    max_value: 0.00025
    steps: null
    step_decay_scale: null
    cosine_decay_type: 1
    linear_type: null # 'epoch' or 'batch'

log_freq: 5
eval_freq:
    '500': 10
    '800': 5
    '900': 2
    '950': 1
